# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_proveedore_clabe'),
        ('c_olimpo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('a_favor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='olimpo_auxiliar_proveedor_id', to='main.Proveedore')),
                ('condomino', models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, related_name='olimpo_auxiliar_condomino_id', to='c_olimpo.Condomino')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CuentaContable', verbose_name='Cuenta Contable')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olimpo_auxiliar_tipo_movimiento_id', to='main.TipoMovimiento')),
            ],
            options={
                'ordering': ['fecha'],
                'db_table': 'olimpo_asiento',
                'managed': True,
            },
        ),
    ]
