# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedore',
            name='clabe',
            field=models.CharField(default='0', max_length=18, null=True),
        ),
    ]
